version: 2
jobs:
  build:
    docker:
      - image: minepicco/cci-aws-docker:latest
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: get current global ip address
          command: gip=`curl -X GET https://api.ipify.org`
      - run:
          name: add rule to allow port 80
          command: aws ec2 authorize-security-group-ingress --group-name cci-test --protocol tcp --port 80 --cidr $gip"/32"
      - run:
          name: curl test (ensure curl responses)
          command: curl http://ec2-18-191-70-3.us-east-2.compute.amazonaws.com
      - run:
          name: remove the rule
          command: aws ec2 authorize-security-group-ingress --group-name cci-test --protocol tcp --port 80 --cidr $gip"/32"
