version: 2
jobs:
  build:
    docker:
      - image: minepicco/cci-aws-docker:1.0

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
