version: 2
jobs:
  build:
    docker:
      - image: minepicco/cci-aws-docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: curl test
          command: curl https://www.google.com 
      - run:
          name: get gip
          command: gip=`curl -X GET https://api.ipify.org` && echo "Global IPアドレス："$gip
      - run:
          name: get gip
          command: aws help
