version: 2
jobs:
  build:
    docker:
      - image: circleci/php
    steps:
      #- checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: ping test
          command: ping google.com 
      - run:
          name: get gip
          command: gip=`curl -X GET https://api.ipify.org` && echo "Global IPアドレス："$gip
