version: 2
jobs:
  build:
    docker:
      - image: minepicco/cci-aws-docker:1.0
    steps:
      #- checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: docker ps
          command: docker ps -a
      - run:
          name: ping test
          command: ping google.com 
      - run:
          name: get gip
          command: gip=`curl -X GET https://api.ipify.org` && echo "Global IPアドレス："$gip
